### ISSUE TITLE
Release the v1 version

### ISSUE THREAD

**Issue by xin-hao-awx** [airwallex/AirSkiff#2]
@yusup-airwallex can we release the v1 version of this library?

1. I think the core logic is stable to reach `v1`
2. I want to switch to a new `v2` version which depends on Flink `v1.15`

**Comment by yusup-airwallex** [comment]
Agreed.  I can release v1 today. 

>  I want to switch to a new v2 version which depends on Flink v1.15
Sorry, v2 of what?
